network: mainnet
address: '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9'
startBlock: 0
USDC_ADDRESS: '0x9fe46736679d2d9a65f0992f2272de9f3c7fa6e0'
WETH_ADDRESS: '0x5fbdb2315678afecb367f032d93f642f64180aa3'
WHITELIST_TOKENS:
  - '0xe7f1725e7734ce288f8367e1bb143e90bb3f0512' # WBTC
STABLE_COINS:
