network: rinkeby
address: '0x42789c4D6c5Cc9334fef4da662A57D78771Ce9E5'
startBlock: 11180000
managerAddress: '0x5e090C58E71B86b94fB544b0143363C3414D0579'
managerStartBlock: 11180000

MAX_TIERS: 6
USDC_ADDRESS: '0xc6399e9e8d6d70a2aa1fc6ade21f56567f6c7862'
WETH_ADDRESS: '0xc778417e063141139fce010982780140aa0cd5ab'
WHITELIST_TOKENS:
  - '0xe4f60170d901450920f37dcf10637109e7f17c72' # DAI
  - '0xdac17f958d2ee523a2206206994597c13d831ec7' # USDT
  - '0x0000000000085d4780b73119b644ae5ecd22b376' # TUSD
  - '0x868cac73fe792d68e8e91d0fac94acdb0d385af9' # WBTC
  - '0x5d3a536e4d6dbd6114cc1ead35777bab948e3643' # cDAI
  - '0x39aa39c021dfbae8fac545936693ac917d5e7563' # cUSDC
  - '0x86fadb80d8d2cff3c3680819e4da99c10232ba0f' # EBASE
  - '0x57ab1ec28d129707052df4df418d58a2d46d5f51' # sUSD
  - '0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2' # MKR
  - '0xc00e94cb662c3520282e6f5717214004a7f26888' # COMP
  - '0x514910771af9ca656af840dff83e8264ecf986ca' # LINK
  - '0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f' # SNX
  - '0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e' # YFI
  - '0x111111111117dc0aa78b770fa6a738034120c302' # 1INCH
  - '0xdf5e0e81dff6faf3a7e52ba697820c5e32d806a8' # yCurv
  - '0x956f47f50a910163d8bf957cf5846d573e7f87ca' # FEI
  - '0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0' # MATIC
  - '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9' # AAVE
  - '0x15e4F1fc9a02e36039554531cDdF1C70F0B05364' # TETH (custom)
  - '0x0C58e68883E8c6390255A83a73dfA42b56EC6400' # WBTC (custom)
  - '0xFD709452E12Df357f415D971eE12C7854285a072' # USDT (custom)
  - '0x7C4e4edc8Cda71DfaB107a1A44f6858f36857cA8' # DAI  (custom)
STABLE_COINS:
  - '0xe4f60170d901450920f37dcf10637109e7f17c72' # DAI
  - '0xdac17f958d2ee523a2206206994597c13d831ec7' # USDT
  - '0x0000000000085d4780b73119b644ae5ecd22b376' # TUSD
  - '0x956f47f50a910163d8bf957cf5846d573e7f87ca' # FEI
  - '0x4dd28568d05f09b02220b09c2cb307bfd837cb95' # PRINTS
  - '0xFD709452E12Df357f415D971eE12C7854285a072' # USDT (custom)
  - '0x7C4e4edc8Cda71DfaB107a1A44f6858f36857cA8' # DAI  (custom)
